# Generated by Django 5.1 on 2024-09-04 10:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0002_alter_order_options_alter_orderdetail_options_and_more'),
        ('AESProduct', '0009_product_comment_parent_alter_product_comment_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساختن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('is_delete', models.BooleanField(default=True, verbose_name='حذف کردن')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='زمان اپدیت کردن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WishList', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'محصول مورد علاقه',
                'verbose_name_plural': 'محصولات مورد علاقه',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WishListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('is_deleted', models.BooleanField(default=True, verbose_name='حذف کردن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WishListDetail', to='AESProduct.product', verbose_name='محصول')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WishListDetail', to='AESOrder.order', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'جزییات محصول مورد علاقه',
                'verbose_name_plural': 'جزییات محصولات مورد علاقه',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
