# Generated by Django 5.1 on 2024-09-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0003_wishlist_wishlistdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistdetail',
            old_name='is_deleted',
            new_name='is_delete',
        ),
    ]
