# Generated by Django 5.1 on 2024-09-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0004_rename_is_deleted_wishlistdetail_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف کردن'),
        ),
        migrations.AlterField(
            model_name='wishlistdetail',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف کردن'),
        ),
        migrations.AlterField(
            model_name='wishlistdetail',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WishListDetail', to='AESOrder.order', verbose_name='محصول مورد علاقه'),
        ),
    ]
