# Generated by Django 5.1 on 2024-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0005_alter_wishlist_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پرداخت'),
        ),
    ]
