# Generated by Django 5.1 on 2024-09-04 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0006_alter_order_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ساختن'),
            preserve_default=False,
        ),
    ]
