# Generated by Django 5.1 on 2024-09-04 12:47

import django.core.validators
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0011_alter_wishlistdetail_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='نام در لینک حتما باید انگلیسی باشد')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('off_percent', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='مقدار تخفیف (درصدی)')),
                ('off_tomman', models.IntegerField(blank=True, null=True, verbose_name='مقدار تخفیف (تومان)')),
                ('number', models.IntegerField(verbose_name='دفعات استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف کردن')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
