# Generated by Django 5.1 on 2024-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0012_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='number_by_user',
            field=models.IntegerField(default=1, verbose_name='دفعات استفاده برای هر کاربر'),
        ),
    ]
