# Generated by Django 5.1 on 2024-09-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0013_coupon_number_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت نهایی کل'),
        ),
    ]
