# Generated by Django 5.1 on 2024-09-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0017_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='send_price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت ارسال'),
        ),
    ]
