# Generated by Django 5.1 on 2024-09-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AESOrder', '0018_alter_order_send_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderdetail',
            managers=[
            ],
        ),
    ]
