# Generated by Django 5.1 on 2024-09-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESAccount', '0002_alter_user_options_user_email_validation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='کد ایمیل'),
        ),
    ]
