# Generated by Django 5.1 on 2024-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESAccount', '0003_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='کد پستی'),
        ),
    ]
