# Generated by Django 5.1 on 2024-08-24 18:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('stock', models.IntegerField(verbose_name='موجودی')),
                ('image', models.ImageField(upload_to='products/', verbose_name='عکس')),
                ('rating', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='میانگین ریت ها')),
                ('more_details', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروز رسانی')),
                ('slug', models.SlugField(verbose_name='نام در url (باید انگلیسی باشد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('off', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف')),
                ('new', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان برند')),
                ('slug', models.CharField(max_length=100, verbose_name='نام در url (باید انگلیسی باشد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('products', models.ManyToManyField(to='AESProduct.product', verbose_name='محصولات')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان کتگوری')),
                ('slug', models.CharField(max_length=100, verbose_name='نام در url (باید انگلیسی باشد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('products', models.ManyToManyField(to='AESProduct.product', verbose_name='محصولات')),
            ],
        ),
        migrations.CreateModel(
            name='Product_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل')),
                ('comment', models.TextField(verbose_name='کامنت')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='ریت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AESProduct.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تگ')),
                ('slug', models.CharField(max_length=100, verbose_name='نام در url (باید انگلیسی باشد)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('products', models.ManyToManyField(to='AESProduct.product', verbose_name='محصولات')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AESProduct.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AESProduct.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='سایز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AESProduct.product', verbose_name='محصول')),
            ],
        ),
    ]
