# Generated by Django 5.1 on 2024-09-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0003_alter_product_managers_alter_product_brands_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AESProduct.product_categories', verbose_name='زیر مجموعه'),
        ),
    ]
