# Generated by Django 5.1 on 2024-09-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0004_product_categories_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='AESProduct.product_categories', verbose_name='زیر مجموعه'),
        ),
    ]
