# Generated by Django 5.1 on 2024-09-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0005_alter_product_categories_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False, verbose_name='داشتن سایز برای محصول'),
        ),
        migrations.AlterField(
            model_name='products_gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='AESProduct.product', verbose_name='محصول'),
        ),
    ]
