# Generated by Django 5.1 on 2024-09-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0006_product_has_size_alter_products_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_categories',
            name='products',
            field=models.ManyToManyField(related_name='categories', to='AESProduct.product', verbose_name='محصولات'),
        ),
    ]
