# Generated by Django 5.1 on 2024-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0007_alter_product_categories_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_brands',
            name='products',
            field=models.ManyToManyField(related_name='brands', to='AESProduct.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='product_tags',
            name='products',
            field=models.ManyToManyField(related_name='tags', to='AESProduct.product', verbose_name='محصولات'),
        ),
    ]
