# Generated by Django 5.1 on 2024-09-05 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0009_product_comment_parent_alter_product_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_comment',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='ریت'),
        ),
    ]
