# Generated by Django 5.1 on 2024-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0010_alter_product_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت (تومان)'),
        ),
    ]
