# Generated by Django 5.1 on 2024-09-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0011_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_sizes',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
