# Generated by Django 5.1 on 2024-09-07 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESProduct', '0012_products_sizes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف'),
        ),
    ]
