# Generated by Django 5.1 on 2024-08-26 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 26, 22, 34, 7, 966775)),
        ),
        migrations.AddField(
            model_name='contact_us',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
