# Generated by Django 5.1 on 2024-08-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0002_contact_us_sent_date_contact_us_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
