# Generated by Django 5.1 on 2024-08-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0004_about_us_faqs_footer_link_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='small_title',
            field=models.CharField(default='Since From 2000', max_length=75, verbose_name='متن بالای عنوان'),
            preserve_default=False,
        ),
    ]
