# Generated by Django 5.1 on 2024-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0005_about_us_small_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_team',
            name='costume_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک های دیگر'),
        ),
        migrations.AddField(
            model_name='about_team',
            name='linkin_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک این'),
        ),
        migrations.AddField(
            model_name='about_team',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تلگرام'),
        ),
    ]
