# Generated by Django 5.1 on 2024-08-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0006_about_team_costume_url_about_team_linkin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_features',
            name='sub_title',
            field=models.CharField(default='ویژگی ما', max_length=75, verbose_name='بالای عنوان'),
            preserve_default=False,
        ),
    ]
