# Generated by Django 5.1 on 2024-09-06 10:03

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0007_about_features_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('link_title', models.CharField(max_length=200, verbose_name='نام لینک')),
                ('link', models.URLField(verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
            ],
            options={
                'verbose_name': 'لینک بالا صفحه',
                'verbose_name_plural': 'لینک های بالا صفحه',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
