# Generated by Django 5.1 on 2024-09-07 17:35

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0008_redline'),
        ('AESProduct', '0012_products_sizes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part_1', models.CharField(max_length=150, verbose_name='عنوان اول')),
                ('title_part_2', models.CharField(max_length=150, verbose_name='عنوان دوم')),
                ('repeat', models.IntegerField(default=1, verbose_name='تکرار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
            ],
            options={
                'verbose_name': 'عنوان در بند سیاه صفحه',
                'verbose_name_plural': 'عنوان ها در بند سیاه صفحه',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='redline',
            options={'verbose_name': 'لینک بالا صفحه(خط قرمز قرمز)', 'verbose_name_plural': 'لینک های بالا صفحه(خط قرمز قرمز)'},
        ),
        migrations.CreateModel(
            name='HomeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('sub_title', models.CharField(max_length=50, verbose_name='زیر عنوان')),
                ('link', models.URLField(verbose_name='لینک')),
                ('link_name', models.CharField(max_length=50, verbose_name='نام لینک')),
                ('first_video', models.URLField(verbose_name='لینک ویدیو اول (پیشنهاد در اپلود ان در اپارت)')),
                ('second_video', models.URLField(verbose_name='لینک ویدیو دوم (پیشنهاد در اپلود ان در اپارت)')),
                ('active_DealOfTheWeek', models.BooleanField(default=True, verbose_name='فعال قسمت پیشنهادات ویژه')),
                ('active_BlackBelt', models.BooleanField(default=True, verbose_name='فعال قسمت  بند سیاه صفحه')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AESProduct.product', verbose_name='محصول ویژه')),
            ],
            options={
                'verbose_name': 'تنظیم صفحه اصلی',
                'verbose_name_plural': 'تنظیمات صفحه اصلی',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DealOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('content', models.CharField(max_length=250, verbose_name='زیر عنوان')),
                ('sub_content', models.CharField(max_length=250, verbose_name='عنوان تشفیقی پایین صفحه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DealOfTheWeek', to='AESHome.homeindex', verbose_name='مربوط به کدوم صفحه')),
            ],
            options={
                'verbose_name': 'پیشنهاد  ویژه هفته',
                'verbose_name_plural': 'پیشنهاد های ویژه هفته',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HomeIndexNewCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/HomeIndexNewCollections/', verbose_name='عکس')),
                ('title', models.CharField(max_length=150)),
                ('link', models.URLField(verbose_name='لینک به صفحه مربوط')),
                ('link_name', models.CharField(max_length=50, verbose_name='نام لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HomeIndexNewCollections', to='AESHome.homeindex', verbose_name='مربوط به کدوم صفحه')),
            ],
            options={
                'verbose_name': 'پست  بالای صفحه اصلی',
                'verbose_name_plural': 'پست های بالای صفحه اصلی',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
