# Generated by Django 5.1 on 2024-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0009_blackbelt_alter_redline_options_homeindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeindexnewcollections',
            name='sub_title',
            field=models.CharField(default='ok', max_length=50, verbose_name='زیر عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeindexnewcollections',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
    ]
