# Generated by Django 5.1 on 2024-09-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0010_homeindexnewcollections_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeindex',
            name='created',
            field=models.DateField(verbose_name='زمان ساخت'),
        ),
    ]
