# Generated by Django 5.1 on 2024-09-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0011_alter_homeindex_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoftheweek',
            name='image',
            field=models.ImageField(null=True, upload_to='image/DealOfTheWeek/', verbose_name='عکس'),
        ),
    ]
