# Generated by Django 5.1 on 2024-09-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AESHome', '0012_dealoftheweek_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealoftheweek',
            name='home',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DealOfTheWeek', to='AESHome.homeindex', verbose_name='مربوط به کدوم صفحه'),
        ),
    ]
